name: OpenAI Feedback

on:
  issues:
    types:
      - opened

jobs:
  run_feedback_script:
    runs-on: self-hosted


    steps:
      - name: Check out repository
        uses: actions/checkout@v3

#      - name: Set Up Virtual Environment
#        run: |
#          python3 -m venv feedback_venv
#          source feedback_venv/bin/activate
#          python3 -m pip install --upgrade pip
#          pip install openai

      - name: Run Feedback Script
        run: |
          source feedback_venv/bin/activate
          python3 

      - name: Push Feedback
        run: |
          git add feedback/*
          git commit -m "Feedback File"
          git push
