name: Feedback

on:
  issues:
    types:
      - opened

jobs:
  run_feedback_script:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Resolve Parent Directory
        run: |
          PARENT_DIR="../../../.."
          echo "PARENT_DIR=$PARENT_DIR" >> $GITHUB_ENV

      - name: Run Feedback Script
        run: |
          source "${{ env.PARENT_DIR }}/feedback_venv/bin/activate"
          python3 "${{ env.PARENT_DIR }}/feedback/feedback.py" "$(pwd)"

      - name: Push Feedback
        run: |
          git add feedback/*
          git commit -m "Feedback File"
          git push
