name: Get Auto Feedback

on:
  issues:
    types:
      - opened

jobs:
  trigger-external:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger external workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: Auto-grading/AutoFeedbackRunner  # External repo
          workflow: auto_feedback.yml  # External workflow file
          ref: main  # Branch or tag of the external repo
